### ISSUE TITLE
ModuleNotFoundError: No module named 'diffusion_webui.controlnet_v1_1'

### ISSUE THREAD

**Issue by zhoujian1028** [liangwq/LLM_StableDiffusion_Studio#1]

**Comment by liangwq** [comment]
你把具体报错贴上来
这应该就是文件地址问题
这个是文件路径diffusion_webui
contronet1.1的路径controlnet_v1_1

**Comment by zhoujian1028** [comment]
![image](https://user-images.githubusercontent.com/6960679/233825675-27312757-4e46-470b-ae9b-79c3bba4fc0c.png)
![image](https://user-images.githubusercontent.com/6960679/233825702-3757a53e-0110-4355-aa16-c34adbb1da75.png)

**Comment by liangwq** [comment]
> ![image](https://user-images.githubusercontent.com/6960679/233825675-27312757-4e46-470b-ae9b-79c3bba4fc0c.png) ![image](https://user-images.githubusercontent.com/6960679/233825702-3757a53e-0110-4355-aa16-c34adbb1da75.png)

今晚把这部分code上传上来

**Comment by zhoujian1028** [comment]
谢谢
